### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by ghost** [EtoileLion/Project-Scripto#6]
Not sure if this is User error or script error, but I have determined that  the script fails the moment it gets to the Actual naming of a house with the following error on the output console. 

`Line 70: 	setTimeout(function() { sendChat("The Sorting Hat",'/emas "The Sorting Hat" '+sorting_messages.emote[Math.floor(Math.random() * sorting_messages.emote.length)].replace("#CHARNAME#",charname).replace("#HOUSE#",house.toUpperCase())) },7500);`

API Output Console
Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your scripts and click the "Save Script" button and we'll attempt to start running them again. More info...

For reference, the error message generated was: TypeError: Cannot read property 'toUpperCase' of undefined
TypeError: Cannot read property 'toUpperCase' of undefined
    at Timeout._onTimeout (apiscript.js:70:218)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by ghost** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/66531471/83952364-579c9e80-a830-11ea-85b4-02faec43d473.png)

**Comment by EtoileLion** [comment]
Interesting. What traits does the character you were using have? (So that I can try and replicate the issue to see where it might be happening)

**Comment by ghost** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/66531471/83966894-ec48e000-a8b4-11ea-9b40-0381d194ec35.png)

**Comment by ghost** [comment]
I am fairly New to scripting, but was testing this out for a new Harry potter campaign that I am looking to set up, so though i don't know much regarding how it works, or understand it, I can deliver error logs. hope the new screenshot helps!

**Comment by EtoileLion** [comment]
Odd. When i created this script, roll20's behavior on Math.max was apparently different, otherwise this code would never have worked.

Fix is to apply a spread operator to the Math.max function used in the score comparator. 

A new version of sortinghat.js has been uploaded.

**Comment by ghost** [comment]
Wonderful - thank you, that is much appreciated.
